/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,ts,jsx,tsx}",
    "./containers/**/*.{js,ts,jsx,tsx}",
    "./features/**/*.{js,ts,jsx,tsx}",
    "./layout/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    "rotate-0",
    "rotate-5",
    "rotate-15",
    "rotate-35",
    "rotate-45",
    "rotate-65",
    "rotate-75",
    "bg-collection-rose",
    "bg-collection-fuchsia",
    "bg-collection-violet",
    "bg-collection-rouge",
    "bg-collection-corail",
    "bg-collection-orange",
    "bg-collection-jaune",
    "bg-collection-vert",
    "bg-collection-bleu",
    "bg-collection-noir",
    "bg-collection-gris",
    "bg-collection-blanc",
    "bg-collection-beige",
    "bg-collection-marron",
    "bg-collection-dore",
    "bg-collection-argente",
    "bg-collection-parme",
    "bg-collection-turquoise",
    "bg-collection-bordeaux",
    "bg-collection-camel",
    "text-collection-rose",
    "text-collection-fuchsia",
    "text-collection-violet",
    "text-collection-rouge",
    "text-collection-corail",
    "text-collection-orange",
    "text-collection-jaune",
    "text-collection-vert",
    "text-collection-bleu",
    "text-collection-noir",
    "text-collection-gris",
    "text-collection-blanc",
    "text-collection-beige",
    "text-collection-marron",
    "text-collection-dore",
    "text-collection-argente",
    "text-collection-parme",
    "text-collection-turquoise",
    "text-collection-bordeaux",
    "text-collection-camel",
    "border-success",
    "border-info",
    "border-waring",
    "border-alert",
    "border-missing-size",
    "text-success-accent",
    "text-info-accent",
    "text-warning-accent",
    "text-alert-accent",
    "text-missing-size-accent",
  ],
  theme: {
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1080px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1707px",
    },
    extend: {
      fontFamily: {
        mss: "var(--mss)",
        quicksand: "var(--quicksand)",
        lexend: "var(--lexend)",
      },
      colors: {
        primary: {
          DEFAULT: "#21ec95",
        },
        grey: {
          darkest: "#46413B",
          darker: "#847C76",
          medium: "#B1A9A2",
          lighter: "#E6D3C2",
          lightest: "#FFFCFA",
        },
        shadow: {
          foreground: "#9B8678",
          grey: "#77716D",
        },
        surface: "#070606",
        accent: "#88319C",
        foreground: "#A79280",
        halftone: "#EFEBE7",
        background: "#FFF5ED",
        toned: "#8F3728",
        stars: "#E9F1F0",
        peps: {
          major: "#0aaacf",
          oldmajor: "#0089A9",
          minor: "#DFFBFB",
        },
        ldc: {
          major: "#EB1923",
          minor: "#FFA2A2",
        },
        alert: {
          accent: "#660051",
          DEFAULT: "#FD00C8",
          muted: "#FDD8FD",
        },
        warning: {
          accent: "#562815",
          DEFAULT: "#D9805B",
          muted: "#FFE0D6",
        },
        "missing-size": {
          accent: "#562815",
          DEFAULT: "#D9805B",
          muted: "#FFE0D6",
        },
        info: {
          accent: "#002D57",
          DEFAULT: "#0061BB",
          muted: "#BDDFFF",
        },
        success: {
          accent: "#313B07",
          DEFAULT: "#A2C617",
          muted: "#E1F6A4",
        },
        collection: {
          rose: "#FCAEB9",
          fuchsia: "#C30873",
          violet: "#8F15DA",
          rouge: "#E10000",
          corail: "#F86D60",
          orange: "#FF9A61",
          jaune: "#FFC700",
          vert: "#35A43A",
          bleu: "#0032E1",
          noir: "#000000",
          gris: "#ACACAC",
          blanc: "#F0F0F0",
          beige: "#F7E9D9",
          marron: "#621212",
          dore: "#FAFAD2",
          argente: "#C0C0C0",
          parme: "#cfa0e9",
          marine: "#000080",
          bordeaux: "#6d071a",
          camel: "#bf8a3d"
        },
      },
      transitionProperty: {
        background: "background",
      },
      width: {
        stickerMobil: "calc(60px + 13vw)",
        entretien: "calc(100% - 56px)",
      },
      height: {
        stickerMobil: "calc(60px + 13vw)",
        ctaHero: "calc(40vh - 38px)",
        blobHero: "calc(60vh - 38px)",
      },
      inset: {
        sticker: "calc(36% + 3rem)",
      },
      translate: {
        aboutMobile: "calc(25% - 5vw)",
        aboutSm: "calc(25% - 10vw)",
      },
      rotate: {
        5: "5deg",
        15: "15deg",
        35: "35deg",
        35: "35deg",
        65: "65deg",
        75: "75deg",
      },
      transitionTimingFunction: {
        blob: "cubic-bezier(.44,-0.29,.61,1.43)",
        blobProduct: "cubic-bezier(0.68,-0.6,0.32,1.6)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("tailwindcss-text-fill")],
};
